version: "3.9"

volumes:
    db:
    logs:
        driver: local

networks:
    slim:
        
services:
    app:
        container_name: app_slim
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APP_PORT: 8080
            APP_URL: http://localhost
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: slimdb
            DB_USERNAME: slim
            DB_PASSWORD: secret
        ports:
            - 8080:8080
        volumes:
            - ./slim:/var/www/html
        depends_on:
            - db
        networks:
            - slim

    db:
        container_name: db_slim
        image: mariadb:10.5.2
        volumes:
            - db:/var/lib/mysql
        environment:
            MARIADB_DATABASE: slimdb
            MARIADB_USER: slim
            MARIADB_PASSWORD: secret
            MARIADB_ROOT_PASSWORD: secret
            TZ: "Asia/Jakarta"
        ports:
            - "3306:3306"
        networks:
            - slim

    pma:
        container_name: pma-slim
        image: phpmyadmin:latest
        depends_on:
            - db
        links:
            - db
        ports:
            - 8082:80
        networks:
            - slim
